# Generated by Django 5.2.7 on 2025-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=50)),
                ('ap_materno', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
    ]
